### ISSUE TITLE
Spracheinstellung springt zurück nach Wechseln der Seite

### ISSUE THREAD

**Issue by emmaalouu** [kultursphaere-sh/kulturfinder.sh-frontend#12]
Wenn man auf der Startseite die Sprache ändert und danach auf eine Kachel klickt, z.B. auf Filter oder Karte, springt die Sprache wieder zurück auf die davor eingestellte Sprache. Wenn man dann wieder zurück auf die Startseite geht, erneut die Sprache ändert und auf eine Kachel klickt, wird die Spracheinstellung beibehalten.

**Comment by nigina23** [comment]
Der Fehler wurde getestet und die Spracheinstellung springt nach dem Sprachwechsel nicht zurück.

**Comment by tjorbo** [comment]
@nigina23 👍
