### ISSUE TITLE
Seitenbeschreibung mit Institutionsdaten

### ISSUE THREAD

**Issue by tjorbo** [kultursphaere-sh/kulturfinder.sh-frontend#59]
Als Benutzerin möchte ich beim Teilen einer Institutions-URL über bspw. Messenger statt einem allgemeinen Erklärungstext für den Kulturfinder, eine Beschreibung der Institution (inklusive Institutionsbild) sehen. Zusätzlich verbessert sich hierdurch die Auffindbarkeit (SEO) der Institutionen/des Kulturfinders.

---

Änderung: wir haben festgestellt, dass Drittanwendungen wie Slack oder Whatsapp kein Javascript ausführen, um die Informationen zu laden. Das beutet, wir keine dynamischen Beschreibungen oder Bild-URLs bereitstellen können.

Wir nutzen dieses Ticket, um die Freigabe-Funktion (in Vue, in der Details-View) um den Beschreibungstext zu erweitern. So erhalten wir zwar kein Logo und keine dynamische Beschreibung, aber zusätzlichen Text in der an den User mitgegebenen Nachricht.

Statt: 

`https://kulturfinder.sh/act0002338`

senden wir

`https://kulturfinder.sh/de/institutions/dashboard/details/Speicher%20Husum%20e.V. Speicher Husum e.V. im kulturfinder.sh - Konzerte, Lesungen, Vorträge, Theater - Der Speicher Husum bietet ein vielfältiges, anspruchsvolles Kulturprogramm, das zu gesellschaftlicher Auseinandersetzung einlädt. Die Angebote reichen von Unterhaltung bis Kontroverse und stehen für Toleranz für unterschiedliche Kulturen und Lebensstile.

**Comment by Bolaji06** [comment]
Hallo, @tjorbo  wird gerne an diesem Problem arbeiten

**Comment by tjorbo** [comment]
Hey @Bolaji06 Schön, dass du helfen möchtest! Du bist herzlich willkommen und ich werde vermerken, dass du an dem Issue arbeitest.

Wir arbeiten noch an einer besseren Beschreibung, um den Einstieg zu erleichtern. (Readme und Contributing)

Wenn du Fragen hast, kannst du sie gerne hier kommentieren, @tradiscantia oder mich anschreiben.

**Comment by Bolaji06** [comment]
Thanks for letting me work on the project @tjorbo . Will send a PR as soon as possible

**Comment by Bolaji06** [comment]
Hallo @tjorbo , ich konnte keine Lösung für das Problem finden, da Vue nicht mein Fachgebiet ist. Das tut mir leid.

**Comment by tjorbo** [comment]
Hey @Bolaji06, das ist gar kein Problem! Hab eine schöne Woche.

**Comment by tjorbo** [comment]
Da wir eine SPA ohne SSR verwenden, kann dieses Ticket nicht umgesetzt werden.
