### ISSUE TITLE
Platzhalter für nicht vorhandene Fotos

### ISSUE THREAD

**Issue by tjorbo** [kultursphaere-sh/kulturfinder.sh-frontend#66]
Als Frontend möchte ich flexibel darauf reagieren können, wenn mir das Backend keine Bild-Datei liefert. Hierfür möchte ich ein Bild in den Assets haben, welches dann angezeigt werden kann.

**Comment by Florabell266** [comment]
![bremerhaven_bunt](https://github.com/kultursphaere-sh/kulturfinder.sh-frontend/assets/148206772/3e547637-5e76-44e3-8ed0-5dbd23ab28c8)
![bremen_bunt](https://github.com/kultursphaere-sh/kulturfinder.sh-frontend/assets/148206772/e3a0f860-419a-406f-ae25-35b72f1c5b4c)
